// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0aHOZ_HVOnh7vOwJCbTM_UA3xmQn1RJE',
    appId: '1:1003963632945:web:de523b8ccf1155b4497410',
    messagingSenderId: '1003963632945',
    projectId: 'inventory-app-bplpriya',
    authDomain: 'inventory-app-bplpriya.firebaseapp.com',
    storageBucket: 'inventory-app-bplpriya.firebasestorage.app',
    measurementId: 'G-P4HSP3QQH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Hdlh-DsOtNKdHMsbZ7UmC3XOeO_FnNo',
    appId: '1:1003963632945:android:6b646d2c7cf999c5497410',
    messagingSenderId: '1003963632945',
    projectId: 'inventory-app-bplpriya',
    storageBucket: 'inventory-app-bplpriya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6662YFl9nQo1dNtvUwcz1jAZ_4wdCNyM',
    appId: '1:1003963632945:ios:e5fc02678c8e371e497410',
    messagingSenderId: '1003963632945',
    projectId: 'inventory-app-bplpriya',
    storageBucket: 'inventory-app-bplpriya.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6662YFl9nQo1dNtvUwcz1jAZ_4wdCNyM',
    appId: '1:1003963632945:ios:e5fc02678c8e371e497410',
    messagingSenderId: '1003963632945',
    projectId: 'inventory-app-bplpriya',
    storageBucket: 'inventory-app-bplpriya.firebasestorage.app',
    iosBundleId: 'com.example.inclass15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0aHOZ_HVOnh7vOwJCbTM_UA3xmQn1RJE',
    appId: '1:1003963632945:web:a5bc8c967b19fa8f497410',
    messagingSenderId: '1003963632945',
    projectId: 'inventory-app-bplpriya',
    authDomain: 'inventory-app-bplpriya.firebaseapp.com',
    storageBucket: 'inventory-app-bplpriya.firebasestorage.app',
    measurementId: 'G-CB7BMD19Q4',
  );
}
